modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "gibmescarves"
version = "1.0.0"
displayName = "GibMeScarves"
displayURL = "https://github.com/CloverCard"
credits = "https://github.com/CloverCard"
authors = "https://github.com/CloverCard"
description = '''
Adds a command to give server cosmetics.
'''

[[dependencies.gibmescarves]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gibmescarves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"


[[dependencies.gibmescarves]]
modId = "pixelmon"
mandatory = true
versionRange = "[9.1.5,)"
ordering = "NONE"
side = "BOTH"